// Destinations data
export const destinations = [
  {
    id: 1,
    name: 'Bali, Indonesia',
    country: 'Indonesia',
    region: 'Asia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    description: 'Tropical paradise with stunning temples and beaches',
    startingPrice: 45000,
    duration: '5 Days / 4 Nights',
    rating: 4.9,
    reviews: 234,
    featured: true,
  },
  {
    id: 2,
    name: 'Swiss Alps',
    country: 'Switzerland',
    region: 'Europe',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80',
    description: 'Breathtaking mountain views and pristine landscapes',
    startingPrice: 125000,
    duration: '7 Days / 6 Nights',
    rating: 4.8,
    reviews: 189,
    featured: true,
  },
  {
    id: 3,
    name: 'Santorini, Greece',
    country: 'Greece',
    region: 'Europe',
    image: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80',
    description: 'Iconic white buildings and stunning sunsets',
    startingPrice: 95000,
    duration: '6 Days / 5 Nights',
    rating: 4.9,
    reviews: 312,
    featured: true,
  },
  {
    id: 4,
    name: 'Dubai, UAE',
    country: 'UAE',
    region: 'Middle East',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    description: 'Luxury shopping and ultramodern architecture',
    startingPrice: 65000,
    duration: '5 Days / 4 Nights',
    rating: 4.7,
    reviews: 456,
    featured: true,
  },
  {
    id: 5,
    name: 'Maldives',
    country: 'Maldives',
    region: 'Asia',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
    description: 'Overwater villas and crystal-clear waters',
    startingPrice: 150000,
    duration: '5 Days / 4 Nights',
    rating: 5.0,
    reviews: 278,
    featured: true,
  },
  {
    id: 6,
    name: 'Paris, France',
    country: 'France',
    region: 'Europe',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    description: 'City of love with iconic landmarks',
    startingPrice: 110000,
    duration: '6 Days / 5 Nights',
    rating: 4.8,
    reviews: 567,
    featured: false,
  },
  {
    id: 7,
    name: 'Kerala, India',
    country: 'India',
    region: 'Asia',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    description: 'Serene backwaters and lush greenery',
    startingPrice: 25000,
    duration: '4 Days / 3 Nights',
    rating: 4.6,
    reviews: 890,
    featured: false,
  },
  {
    id: 8,
    name: 'Tokyo, Japan',
    country: 'Japan',
    region: 'Asia',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    description: 'Ancient traditions meet futuristic innovation',
    startingPrice: 135000,
    duration: '8 Days / 7 Nights',
    rating: 4.9,
    reviews: 345,
    featured: false,
  },
]

// Packages with pricing
export const packages = [
  {
    id: 1,
    name: 'Explorer',
    description: 'Perfect for budget-conscious travelers',
    price: 35000,
    features: [
      '3-star hotel accommodation',
      'Airport transfers',
      'Daily breakfast',
      'City tour included',
      'Travel insurance',
    ],
    notIncluded: ['Flight tickets', 'Lunch & Dinner', 'Personal expenses'],
    popular: false,
  },
  {
    id: 2,
    name: 'Premium',
    description: 'Best value for an unforgettable experience',
    price: 75000,
    features: [
      '4-star hotel accommodation',
      'Airport transfers',
      'All meals included',
      'Guided tours',
      'Travel insurance',
      'Local experiences',
      'Welcome gift',
    ],
    notIncluded: ['Flight tickets', 'Personal expenses'],
    popular: true,
  },
  {
    id: 3,
    name: 'Luxury',
    description: 'The ultimate travel experience',
    price: 150000,
    features: [
      '5-star luxury resort',
      'Private airport transfers',
      'All-inclusive dining',
      'Private guided tours',
      'Comprehensive travel insurance',
      'Exclusive experiences',
      'Spa treatments',
      'Flight tickets included',
      'Personal concierge',
    ],
    notIncluded: ['Personal shopping'],
    popular: false,
  },
]

// Services
export const services = [
  {
    id: 1,
    icon: 'Plane',
    title: 'Flight Booking',
    description: 'Best deals on domestic and international flights with premium airlines.',
  },
  {
    id: 2,
    icon: 'Hotel',
    title: 'Hotel Reservations',
    description: 'Handpicked accommodations from budget-friendly to luxury resorts.',
  },
  {
    id: 3,
    icon: 'FileCheck',
    title: 'Visa Assistance',
    description: 'Hassle-free visa processing and documentation support for all countries.',
  },
  {
    id: 4,
    icon: 'Ship',
    title: 'Cruise Packages',
    description: 'Luxury cruise experiences across the Mediterranean, Caribbean, and beyond.',
  },
  {
    id: 5,
    icon: 'Church',
    title: 'Sacred Temple Visits',
    description: 'Spiritual journeys to sacred temples, shrines, and pilgrimage sites worldwide.',
  },
  {
    id: 6,
    icon: 'Map',
    title: 'Tour Packages',
    description: 'Curated travel packages designed for unforgettable experiences.',
  },
  {
    id: 7,
    icon: 'Compass',
    title: 'Adventure Tours',
    description: 'Thrilling adventures from trekking to water sports and beyond.',
  },
  {
    id: 8,
    icon: 'Heart',
    title: 'Honeymoon Specials',
    description: 'Romantic getaways crafted for couples seeking magical moments.',
  },
  {
    id: 9,
    icon: 'Users',
    title: 'Group Tours',
    description: 'Budget-friendly group travel with like-minded explorers.',
  },
]

// Testimonials
export const testimonials = [
  {
    id: 1,
    name: 'Priya Sharma',
    location: 'Mumbai, India',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    rating: 5,
    text: 'Goed Travels made our Bali honeymoon absolutely magical! Every detail was perfectly planned. The team went above and beyond to ensure we had the trip of a lifetime.',
    trip: 'Bali Honeymoon Package',
  },
  {
    id: 2,
    name: 'Rajesh Kumar',
    location: 'Delhi, India',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    rating: 5,
    text: 'The Swiss Alps tour was breathtaking! The itinerary was well-planned with perfect balance of activities and leisure. Highly recommend their premium packages.',
    trip: 'Swiss Alps Adventure',
  },
  {
    id: 3,
    name: 'Ananya Reddy',
    location: 'Bangalore, India',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80',
    rating: 5,
    text: 'Our family trip to Dubai was seamless from start to finish. The kids loved every moment! The attention to detail and 24/7 support made all the difference.',
    trip: 'Dubai Family Package',
  },
  {
    id: 4,
    name: 'Vikram Singh',
    location: 'Jaipur, India',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80',
    rating: 5,
    text: 'Exceptional service! They handled our corporate retreat to Maldives flawlessly. Professional, responsive, and truly understand luxury travel.',
    trip: 'Maldives Corporate Retreat',
  },
]

// Stats
export const stats = [
  { number: '15K+', label: 'Happy Travelers' },
  { number: '50+', label: 'Destinations' },
  { number: '98%', label: 'Satisfaction Rate' },
  { number: '10+', label: 'Years Experience' },
]

// Gallery images
export const galleryImages = [
  {
    id: 1,
    src: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    alt: 'Mountain landscape',
    category: 'Nature',
  },
  {
    id: 2,
    src: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
    alt: 'Luxury resort pool',
    category: 'Resorts',
  },
  {
    id: 3,
    src: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80',
    alt: 'Tropical beach',
    category: 'Beaches',
  },
  {
    id: 4,
    src: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80',
    alt: 'Japanese temple',
    category: 'Culture',
  },
  {
    id: 5,
    src: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=600&q=80',
    alt: 'Scenic viewpoint',
    category: 'Adventure',
  },
  {
    id: 6,
    src: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
    alt: 'Luxury hotel room',
    category: 'Resorts',
  },
  {
    id: 7,
    src: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&q=80',
    alt: 'Paris Eiffel Tower',
    category: 'Cities',
  },
  {
    id: 8,
    src: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80',
    alt: 'Maldives overwater villa',
    category: 'Beaches',
  },
]

// Client logos (using placeholder names)
export const clients = [
  'Tech Corp International',
  'Global Finance Ltd',
  'Innovate Solutions',
  'Premier Industries',
  'Apex Technologies',
  'Stellar Enterprises',
]

